services:
  redis:
    image: redis:latest
    container_name: redis_container_skarybet  # Nombre único para este contenedor
    ports:
      - "6379:6379"
    volumes:
      - redis_skarybet:/data
    restart: always

volumes:
  redis_skarybet: